application: courses-epfl
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: epfl.courses.course_catalog.app

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
