#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Static data about instructors and courses."""

__author__ = "stefan.bucur@epfl.ch (Stefan Bucur)"


################################################################################
# Course catalog
################################################################################

# TODO(bucur): Extract this data automatically.
# This content may become outdated.

RAW_SECTIONS = {
 'AR': 'Architecture',
 'AR_ECH': 'Architecture Exchange',
 'CGC' : 'Chemistry and Chemical Engineering',
 'CGC_CHIM': 'Molecular and Biological Chemistry',
 'CGC_ING': 'Chemical Engineering and Biotechnology',
 'EDIC': 'Computer, Communication and Information Sciences',
 'EDMT': 'Management of Technology',
 'EDNE': 'Neuroscience',
 'EL': 'Electrical and Electronics Engineering',
 'EME_MES': 'Energy Management and Sustainability',
 'ENAC': 'Architecture, Civil and Environmental Engineering',
 'GC': 'Civil Engineering',
 'GM': 'Mechanical Engineering',
 'HPLANS': 'Hors Plans',
 'IF': 'Financial Engineering',
 'IN': 'Computer Science',
 'ING_MATH': 'Mathematics Engineering',
 'ING_PHYS': 'Physics Engineering',
 'MA': 'Mathematics',
 'MATH': 'Mathematics',
 'MA_CO': 'Computational Science and Engineering',
 'MIN_AREA_CULTURAL': 'Area and Cultural Studies minor',
 'MIN_BIOCOMP': 'Biocomputing minor',
 'MIN_BIOMED': 'Biomedical Technologies minor',
 'MIN_BIOTECH': 'Biotechnology minor',
 'MIN_DEV_TER': 'Territorial Development minor',
 'MIN_ENER': 'Energy minor',
 'MIN_IN_SEC': 'Information Security minor',
 'MIN_MTE': 'Management of Technology and Entrepreneurship minor',
 'MIN_TEC_SPACE': 'Space Technologies minor',
 'MNIS': 'Micro and Nanotechnologies for Integrated Systems',
 'MT': 'Microengineering',
 'MTE': 'Management of Technology',
 'MX': 'Materials Science and Engineering',
 'PH': 'Physics',
 'PHYS': 'Physics',
 'PH_NE': 'Nuclear engineering',
 'SC': 'Communication Systems',
 'SC_EPFL': 'Communication Systems',
 'SHS': 'Humanities and Social Sciences',
 'SIE': 'Environmental Sciences and Engineering',
 'SV': 'Life Sciences and Technologies',
 'SV_B': 'Bioengineering',
 'SV_STV': 'Life Sciences and Technologies',
 'UNIL_BIU': 'UNIL - Biologie',
 'UNIL_CSU': 'UNIL - Collège des sciences',
 'UNIL_GEU': 'UNIL - Géosciences',
 'UNIL_HEC': 'UNIL - Hautes études commerciales',
 'UNIL_MEU': 'UNIL - Médicine',
 'UNIL_PHU': 'UNIL - Pharmacie',
 'UNIL_SFU': 'UNIL - Sciences forensiques',
}


def _OrganizeSections(sections):
  result_dict = {}
  for section in sections:
    key = section.split("_")[0]
    result_dict.setdefault(key, []).append(section)
    
  return [ [ key ] + result_dict[key] for key in sorted(result_dict.keys()) ]

SECTIONS = _OrganizeSections(RAW_SECTIONS)


EXAM = [
  "During the semester",
  "Oral",
  "Term paper",
  "Written"
]

CREDITS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 20, 30]

COEFFICIENT = [ 0.5, 1.0, 1.5, 2.0, 3.0, 4.0 ]

LECTURE_TIME = [ 1, 2, 3, 4, 5, 6 ]

RECITATION_TIME = [ 1, 2, 3, 4 ]

PROJECT_TIME = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 16 ]

RAW_STUDY_PLANS = [
  "AR-BA1",
  "AR-BA2",
  "AR-BA3",
  "AR-BA4",
  "AR-BA5",
  "AR-BA6",
  "AR-E",
  "AR-H",
  "AR-MA1",
  "AR-MA2",
  "AR-MA3",
  "AR-PME",
  "AR-PMH",
  "AUDIT-E",
  "AUDIT-H",
  "CGC-BA1",
  "CGC-BA2",
  "CGC-BA3",
  "CGC-BA4",
  "CGC-BA5",
  "CGC-BA6",
  "CGC-MA1",
  "CGC-MA2",
  "CGC-MA3",
  "CGC-PME",
  "CGC-PMH",
  "EDIC",
  "EDMT",
  "EDNE",
  "EL-BA1",
  "EL-BA2",
  "EL-BA3",
  "EL-BA4",
  "EL-BA5",
  "EL-BA6",
  "EL-MA1",
  "EL-MA2",
  "EL-MA3",
  "EL-MA4",
  "EL-PME",
  "EL-PMH",
  "EME-MA1",
  "EME-MA2",
  "ENAC-BA4",
  "ENAC-BA6",
  "GC-BA1",
  "GC-BA2",
  "GC-BA3",
  "GC-BA4",
  "GC-BA5",
  "GC-BA6",
  "GC-MA1",
  "GC-MA2",
  "GC-MA3",
  "GC-PME",
  "GC-PMH",
  "GM-BA1",
  "GM-BA2",
  "GM-BA3",
  "GM-BA4",
  "GM-BA5",
  "GM-BA6",
  "GM-MA1",
  "GM-MA2",
  "GM-MA3",
  "GM-PME",
  "GM-PMH",
  "HPLANS-E",
  "HPLANS-H",
  "IF-MA1",
  "IF-MA2",
  "IF-MA3",
  "IN-BA1",
  "IN-BA2",
  "IN-BA3",
  "IN-BA4",
  "IN-BA5",
  "IN-BA6",
  "IN-MA1",
  "IN-MA2",
  "IN-MA3",
  "IN-PME",
  "IN-PMH",
  "MA-BA1",
  "MA-BA2",
  "MA-BA3",
  "MA-BA4",
  "MA-BA5",
  "MA-BA6",
  "MA-MA1",
  "MA-MA2",
  "MA-MA3",
  "MA-PME",
  "MA-PMH",
  "MINEUR-E",
  "MINEUR-H",
  "MT-BA1",
  "MT-BA2",
  "MT-BA3",
  "MT-BA4",
  "MT-BA5",
  "MT-BA6",
  "MT-MA1",
  "MT-MA2",
  "MT-MA3",
  "MT-PME",
  "MT-PMH",
  "MTE-MA1",
  "MTE-MA2",
  "MTE-MA3",
  "MTE-PME",
  "MTE-PMH",
  "MX-BA1",
  "MX-BA2",
  "MX-BA3",
  "MX-BA4",
  "MX-BA5",
  "MX-BA6",
  "MX-MA1",
  "MX-MA2",
  "MX-MA3",
  "MX-PME",
  "MX-PMH",
  "PH-BA1",
  "PH-BA2",
  "PH-BA3",
  "PH-BA4",
  "PH-BA5",
  "PH-BA6",
  "PH-MA1",
  "PH-MA2",
  "PH-MA3",
  "PH-MA4",
  "PH-PME",
  "PH-PMH",
  "SC-BA1",
  "SC-BA2",
  "SC-BA3",
  "SC-BA4",
  "SC-BA5",
  "SC-BA6",
  "SC-MA1",
  "SC-MA2",
  "SC-MA3",
  "SC-MA4",
  "SC-PME",
  "SC-PMH",
  "SHS-BA1",
  "SHS-BA2",
  "SHS-BA3",
  "SHS-BA4",
  "SHS-BA5",
  "SHS-BA6",
  "SHS-MA1",
  "SHS-MA2",
  "SIE-BA1",
  "SIE-BA2",
  "SIE-BA3",
  "SIE-BA4",
  "SIE-BA5",
  "SIE-BA6",
  "SIE-MA1",
  "SIE-MA2",
  "SIE-MA3",
  "SIE-PME",
  "SIE-PMH",
  "SV-BA1",
  "SV-BA2",
  "SV-BA3",
  "SV-BA4",
  "SV-BA5",
  "SV-BA6",
  "SV-MA1",
  "SV-MA2",
  "SV-MA3",
  "SV-PME",
  "SV-PMH"
]


################################################################################
# Course description form data
################################################################################

LANGUAGE_CODE = {
  "en": "English",
  "fr": "French",
}

GRADING_CODE = {
  "sem": u"Throughout semester (contrôle continu)",
  "writ": u"Written (exam period)",
  "oral": u"Oral (exam period)",
  "sem_writ": u"Throughout semester + written (exam period)",
  "sem_oral": u"Throughout semester + oral (exam period)",
}

INSTRUCTORS = [
  ("Anastasia", "Ailamaki", "anastasia.ailamaki@epfl.ch"),
  ("George", "Candea", "george.candea@epfl.ch"),
  ("Giovanni", "De Micheli", "giovanni.demicheli@epfl.ch"),
  ("Pierre", "Dillenbourg", "pierre.dillenbourg@epfl.ch"),
  ("Babak", "Falsafi", "babak.falsafi@epfl.ch"),
  ("Boi", "Faltings", "boi.faltings@epfl.ch"),
  ("Pascal", "Fua", "pascal.fua@epfl.ch"),
  ("Wulfram", "Gerstner", "wulfram.gerstner@epfl.ch"),
  ("Roger", "Hersch", "rd.hersch@epfl.ch"),
  ("Jeffrey", "Huang", "jeffrey.huang@epfl.ch"),
  ("Paolo", "Ienne", "paolo.ienne@epfl.ch"),
  ("Christoph", "Koch", "christoph.koch@epfl.ch"),
  ("Bernard", "Moret", "bernard.moret@epfl.ch"),
  ("Martin", "Odersky", "martin.odersky@epfl.ch"),
  ("Mark", "Pauly", "mark.pauly@epfl.ch"),
  ("Claude", "Petitpierre", "claude.petitpierre@epfl.ch"),
  ("Ronan", "Boulic", "ronan.boulic@epfl.ch"),
  ("Christina", "Fragouli", "christina.fragouli@epfl.ch"),
  ("Dejan", "Kostic", "dejan.kostic@epfl.ch"),
  ("Viktor", "Kuncak", "viktor.kuncak@epfl.ch"),
  ("Pearl", "Pu Faltings", "pearl.pu@epfl.ch"),
  ("Martin", "Rajman", "martin.rajman@epfl.ch"),
  ("Matthias", "Seeger", "matthias.seeger@epfl.ch"),
  ("Philippe", "Janson", "philippe.janson@epfl.ch"),
  ("Christian", "Piguet", "christian.piguet@epfl.ch"),
  ("Eduardo", "Sanchez", "eduardo.sanchez@epfl.ch"),
  ("Manuel", "Acevedo", "manuel.acevedo@epfl.ch"),
  ("René", "Beuchat", "rene.beuchat@epfl.ch"),
  ("Jean-Cédric", "Chappelier", "jean-cedric.chappelier@epfl.ch"),
  ("Jean-Luc", "Desbiolles", "jean-luc.desbiolles@epfl.ch"),
  ("Patrick", "Jermann", "patrick.jermann@epfl.ch"),
  ("Ties", "Kluter", "ties.kluter@epfl.ch"),
  ("Hendrik Ole", "Knoche", "hendrik.knoche@epfl.ch"),
  ("Marc", "Lecoultre", "marc.lecoultre@epfl.ch"),
  ("Vincent", "Lepetit", "vincent.lepetit@epfl.ch"),
  ("Thomas", "Lochmatter", "thomas.lochmatter@epfl.ch"),
  ("Jean-Philippe", "Pellet", "jean-philippe.pellet@epfl.ch"),
  ("Pierre-Yves", "Rochat", "pierre-yves.rochat@epfl.ch"),
  ("Jamila", "Sam", "jamila.sam@epfl.ch"),
  ("Michel", "Schinz", "michel.schinz@epfl.ch")
]

INSTRUCTORS_NEW = [
  ("Alain", "Wegmann"),
  ("Aleksander", "Madry"),
  ("Amin", "Shokrollahi"),
  ("Amina", "Chebira"),
  ("Anastasia", "Ailamaki"),
  ("Andrea", "Ridolfi"),
  ("André", "Schiper"),
  ("Arjen", "Lenstra"),
  ("Babak", "Falsafi"),
  ("Bernard", "Moret"),
  ("Bertrand", "Dutoit"),
  ("Bixio", "Rimoldi"),
  ("Boi", "Faltings"),
  ("Catherine", "Monnin"),
  ("Christian", "Piguet"),
  ("Christina", "Fragouli"),
  ("Christine", "Vanoirbeek"),
  ("Christof", "Faller"),
  ("Christoph", "Koch"),
  ("Claude", "Petitpierre"),
  ("Dejan", "Kostic"),
  ("Eduardo", "Sanchez"),
  ("Emre", "Telatar"),
  ("Eytan", "Zysman"),
  ("Friedrich", "Eisenbrand"),
  ("George", "Candea"),
  ("Giovanni", "De Micheli"),
  ("Gregor", "Rainer"),
  ("Hendrik Ole", "Knoche"),
  ("Hubert", "Kirrmann"),
  ("Jamila", "Sam"),
  ("Jean-Cédric", "Chappelier"),
  ("Jean-Dominique", "Decotignie"),
  ("Jean-Luc", "Desbiolles"),
  ("Jean-Philippe", "Pellet"),
  ("Jean-Pierre", "Hubaux"),
  ("Jean-Yves", "Le Boudec"),
  ("Jeffrey", "Huang"),
  ("Joseph", "Sifakis"),
  ("Karl", "Aberer"),
  ("Katerina", "Argyraki"),
  ("Manuel", "Acevedo"),
  ("Marc", "Lecoultre"),
  ("Mark", "Pauly"),
  ("Martin", "Odersky"),
  ("Martin", "Rajman"),
  ("Martin", "Vetterli"),
  ("Matthias", "Grossglauser"),
  ("Matthias", "Seeger"),
  ("Michael", "Gastpar"),
  ("Olivier", "Lévêque"),
  ("Paolo", "Ienne"),
  ("Pascal", "Fua"),
  ("Patrick", "Jermann"),
  ("Patrick", "Thiran"),
  ("Pearl", "Pu Faltings"),
  ("Philippe", "Oechslin"),
  ("Philippe", "Janson"),
  ("Pierre", "Dillenbourg"),
  ("Pierre-Yves", "Rochat"),
  ("Rachid", "Guerraoui"),
  ("René", "Beuchat"),
  ("Roger", "Hersch"),
  ("Ronan", "Boulic"),
  ("Rüdiger", "Urbanke"),
  ("Sabine", "Süsstrunk"),
  ("Schinz", "Michel"),
  ("Serge", "Vaudenay"),
  ("Thomas", "Heinis"),
  ("Thomas", "Lochmatter"),
  ("Ties", "Kluter"),
  ("Viktor", "Kuncak"),
  ("Vincent", "Lepetit"),
  ("Willy", "Zwaenepoel"),
  ("Wulfram", "Gerstner"),
  ("Xiuwei", "Zhang"),
]

PREREQUISITES = [
  ("CS-100", "Introduction aux systèmes informatiques"),
  ("CS-105", "Introduction à la programmation objet"),
  ("CS-106", "Théorie et pratique de la programmation"),
  ("CS-150", "Discrete structures"),
  ("CS-170", "Systèmes logiques  I"),
  ("CS-172", "Systèmes logiques  II"),
  ("CS-198", "Projet de technologie de l'information"),
  ("CS-205", "Programmation avancée"),
  ("CS-206", "Concurrence"),
  ("CS-207", "Programmation orientée système"),
  ("CS-250", "Algorithms"),
  ("CS-251", "Informatique théorique"),
  ("CS-252", "Advanced theoretical computer sciences"),
  ("CS-270", "Architecture des ordinateurs I"),
  ("CS-271", "Architecture des ordinateurs II"),
  ("CS-305", "Software engineering"),
  ("CS-306", "Software development project"),
  ("CS-320", "Compiler construction"),
  ("CS-321", "Informatique du temps réel"),
  ("CS-322", "Introduction to database systems"),
  ("CS-323", "Operating systems"),
  ("CS-330", "Intelligence artificielle"),
  ("CS-341", "Introduction to computer graphics"),
  ("CS-350", "Graph theory applications"),
  ("CS-370", "Introduction to Multiprocessor Architecture"),
  ("CS-398", "Projet en Informatique I"),
  ("COM-101", "Sciences de l'information"),
  ("COM-203", "Digital photography"),
  ("COM-208", "Computer networks"),
  ("COM-300", "Modèles stochastiques pour les communications"),
  ("COM-301", "Sécurité des réseaux"),
  ("COM-302", "Principles of digital communications"),
  ("COM-303", "Signal processing for communications"),
  ("COM-307", "Projet en systemes de communication I"),
  ("EE-204", "Circuits and systems I"),
  ("EE-205", "Circuits and systems II"),
  ("MATH-103", "Analyse I"),
  ("MATH-107", "Analyse II"),
  ("MATH-111b", "Algèbre linéaire"),
  ("MATH-203c", "Analyse III"),
  ("MATH-207b", "Analyse IV"),
  ("MATH-232", "Probabilités et statistiques")
]
