application: courses-epfl
version: 9
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
  
- url: /google85c337d4fdcf0b58\.html
  static_files: static/google85c337d4fdcf0b58.html
  upload: static/google85c337d4fdcf0b58\.html

- url: /static
  static_dir: static

- url: /.*
  script: epfl.courses.main.app

libraries:
- name: jinja2
  version: latest
  
- name: lxml
  version: latest
  
inbound_services:
- warmup
